"""Warm-starting the policy from the heuristic.

    python -m training.clone --games 400 --out checkpoints/cloned.pt
    python -m training.train --resume checkpoints/cloned.pt --iterations 400

Self-play from random initialisation spends its first few million steps rediscovering things
the project already knows: that settlements belong on high-pip vertices, that a city is worth
more than a road, that you do not trade four ore for a sheep. The first run measured that
directly — 0.5% against the heuristic at iteration 0, and roughly 200 iterations to reach
25%, almost all of it spent learning what :mod:`catan.heuristics` states outright.

So the policy is first trained to *imitate* the heuristic — supervised learning on
``(observation, mask) -> action`` — and self-play starts from there. Two things make this
worth doing rather than merely appealing:

**It is cheap.** The dataset is generated by the heuristic playing itself, at engine speed,
with no gradient anywhere. A few hundred games is a few minutes.

**It is not a ceiling.** Cloning sets the starting point, not the objective. Once PPO takes
over, the only thing being maximised is winning, and the heuristic's mistakes are free to be
unlearned. What it cannot do is *invent* a strategy the heuristic never demonstrates — which
is exactly what the self-play half is for.

The value head is trained at the same time, on the eventual outcome of the game each position
came from. A critic that already knows a two-city lead is winning makes every advantage in
the first PPO iteration less noisy.
"""

import argparse
import pathlib
import time

import numpy as np
import torch
from torch import nn

from catan import action_space, encoder
from catan.agents import DIFFICULTY, HeuristicAgent
from catan.env import CatanEnv
from catan.rulesets import RANKED_1V1
from training.net import PolicyValueNet
from training.rollout import TRAINING_MAX_TURNS, outcome


def demonstrate(games=400, max_turns=TRAINING_MAX_TURNS, seed=0, noise=0.0,
                clean_labels=True, log=print):
    """Play ``games`` heuristic-vs-heuristic games and record every real decision.

    Forced decisions are skipped, exactly as in the rollout: there is nothing to imitate
    when there is nothing to choose.

    **Noisy play, clean labels.** A deterministic demonstrator visits one narrow band of
    positions, and a policy cloned from it has never seen the states it will reach the first
    time it plays differently — the standard failure of behaviour cloning. So the games are
    *played* by a noisy teacher, for coverage.

    But the recorded label is what the **noiseless** heuristic would do in that position,
    not what the noisy one did. Training on the noisy choice teaches the student to imitate
    the mistakes as well as the judgement, and it caps the achievable agreement: measured,
    a ``noise=0.35`` teacher agrees with the noiseless one only 71.2% of the time, so no
    learner imitating it could score better than that. Separating the two costs one extra
    heuristic evaluation per decision and nothing else.
    """
    labeller = HeuristicAgent(seed + 424_242, noise=0.0) if clean_labels else None
    observations, masks, actions, values = [], [], [], []
    target = RANKED_1V1.victory_points_to_win
    started = time.perf_counter()

    for game in range(games):
        env = CatanEnv(num_players=2, ruleset=RANKED_1V1, max_turns=max_turns)
        obs, info = env.reset(seed=seed * 100_003 + game)
        agents = {
            1: HeuristicAgent(seed * 7 + game, noise=noise),
            2: HeuristicAgent(seed * 13 + game + 5_000, noise=noise),
        }
        episode = []                       # (obs, mask, action, seat)

        while not info["done"]:
            player = info["player"]
            action = agents[player](obs, info)
            if len(info["legal"]) > 1:
                label = labeller(obs, info) if labeller is not None else action
                episode.append((obs, info["mask"], label, player))
            obs, _, _, _, info = env.step(action)

        for observation, mask, action, seat in episode:
            observations.append(np.asarray(observation, dtype=np.float32))
            masks.append(np.asarray(mask, dtype=bool))
            actions.append(action)
            values.append(outcome(info, seat, target))

        if log and (game + 1) % 50 == 0:
            log(f"  {game + 1}/{games} games, {len(actions):,} decisions, "
                f"{time.perf_counter() - started:.0f}s")

    return (
        torch.as_tensor(np.asarray(observations)),
        torch.as_tensor(np.asarray(masks)),
        torch.as_tensor(np.asarray(actions, dtype=np.int64)),
        torch.as_tensor(np.asarray(values, dtype=np.float32)),
    )


def clone(net, dataset, epochs=10, batch=512, lr=1e-3, value_coef=0.5, holdout=0.1,
          log=print):
    """Train ``net`` to imitate the demonstrations. Returns the per-epoch history.

    Accuracy is reported on a **held-out** slice. Training accuracy on this task rises
    happily while the policy memorises board identity — the tiles section is 27% of the
    observation and constant within a game — so the training number says nothing about
    whether the agent has learned to play.
    """
    observations, masks, actions, values = dataset
    n = len(actions)
    split = int(n * (1 - holdout))
    order = torch.randperm(n)
    train_idx, test_idx = order[:split], order[split:]

    optimizer = torch.optim.Adam(net.parameters(), lr=lr)
    history = []

    for epoch in range(epochs):
        net.train()
        shuffled = train_idx[torch.randperm(len(train_idx))]
        losses = []
        for start in range(0, len(shuffled), batch):
            rows = shuffled[start:start + batch]
            logits, value = net(observations[rows])
            logits = net._apply_mask(logits, masks[rows])

            policy_loss = nn.functional.cross_entropy(logits, actions[rows])
            value_loss = nn.functional.mse_loss(value, values[rows])
            loss = policy_loss + value_coef * value_loss

            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            nn.utils.clip_grad_norm_(net.parameters(), 0.5)
            optimizer.step()
            losses.append((float(policy_loss.detach()), float(value_loss.detach())))

        accuracy, value_error = _score(net, observations, masks, actions, values, test_idx)
        train_accuracy, _ = _score(net, observations, masks, actions, values,
                                   train_idx[:len(test_idx)])
        record = {
            "epoch": epoch,
            "policy_loss": float(np.mean([p for p, _ in losses])),
            "value_loss": float(np.mean([v for _, v in losses])),
            "accuracy": accuracy,
            "train_accuracy": train_accuracy,
            "value_error": value_error,
        }
        history.append(record)
        if log:
            log(f"  epoch {epoch:>2}  loss {record['policy_loss']:.4f}  "
                f"agreement {100 * accuracy:5.1f}% (train {100 * train_accuracy:5.1f}%)  "
                f"value MAE {value_error:.3f}")

    return history


@torch.no_grad()
def _score(net, observations, masks, actions, values, rows):
    net.eval()
    logits, value = net(observations[rows])
    logits = net._apply_mask(logits, masks[rows])
    agreement = float((logits.argmax(dim=-1) == actions[rows]).float().mean())
    error = float((value - values[rows]).abs().mean())
    return agreement, error


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Warm-start a policy by imitating the heuristic agent",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--games", type=int, default=400)
    parser.add_argument("--epochs", type=int, default=10)
    parser.add_argument("--batch", type=int, default=512)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--noise", type=float, default=DIFFICULTY["medium"],
                        help="demonstrator noise; a deterministic teacher shows too few states")
    parser.add_argument("--noisy-labels", action="store_true",
                        help="label with the noisy teacher's actual move rather than the "
                             "noiseless heuristic's; caps achievable agreement at ~71%%")
    parser.add_argument("--hidden", type=int, nargs="+", default=[512, 512])
    parser.add_argument("--net", choices=["flat", "structured"], default="flat")
    parser.add_argument("--max-turns", type=int, default=TRAINING_MAX_TURNS)
    parser.add_argument("--threads", type=int, default=6)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--out", default="checkpoints/cloned.pt")
    args = parser.parse_args(argv)

    torch.set_num_threads(args.threads)
    torch.manual_seed(args.seed)

    print(f"generating {args.games} demonstration games (play noise={args.noise}, "
          f"labels={'noisy' if args.noisy_labels else 'noiseless'})")
    dataset = demonstrate(games=args.games, max_turns=args.max_turns,
                          seed=args.seed, noise=args.noise,
                          clean_labels=not args.noisy_labels)
    print(f"{len(dataset[2]):,} decisions, "
          f"{dataset[0].element_size() * dataset[0].nelement() / 1e6:.0f} MB")

    if args.net == "structured":
        from training.structured_net import StructuredPolicyValueNet

        net = StructuredPolicyValueNet()
    else:
        net = PolicyValueNet(encoder.SIZE, action_space.NUM_ACTIONS,
                             hidden=tuple(args.hidden))
    print(f"{net!r}\ncloning")
    history = clone(net, dataset, epochs=args.epochs, batch=args.batch, lr=args.lr)

    path = pathlib.Path(args.out)
    path.parent.mkdir(parents=True, exist_ok=True)
    torch.save({
        "config": net.config(),
        "weights": net.state_dict(),
        "optimizer": torch.optim.Adam(net.parameters()).state_dict(),
        "pool": None,
        "iteration": 0,
        "history": [],
        "clone_history": history,
    }, path)
    print(f"\nsaved {path}")

    from training.agent import PolicyAgent
    from training.evaluate import evaluate_all, format_result
    print("measuring the cloned policy (200 games each):")
    for name, result in evaluate_all(PolicyAgent(net), games=200).items():
        print(f"  {format_result(name, result)}")
    return net


if __name__ == "__main__":
    main()
